# Generated by Django 5.2.5 on 2025-09-02 09:57

from django.db import migrations
import uuid
def populate_order_id(apps, schema_editor):
    Order = apps.get_model('core', 'Order')
    # برای جلوگیری از برخورد (خیلی بعیده) بررسی می‌کنیم که UUID تکراری نشود
    for order in Order.objects.filter(order_id__isnull=True):
        new_uuid = uuid.uuid4()
        while Order.objects.filter(order_id=new_uuid).exists():
            new_uuid = uuid.uuid4()
        order.order_id = new_uuid
        order.save(update_fields=['order_id'])

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_order_id, reverse_code=migrations.RunPython.noop),
    ]
